In [1]:
import pandas as pd
import numpy as np

In [2]:
#A1
pd.__version__

'2.3.2'

In [3]:
df = pd.read_csv('./data/car_fuel_efficiency.csv')
df

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551


In [4]:
#A2
df.shape

(9704, 11)

In [5]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [6]:
#A3
df.fuel_type.nunique()

2

In [7]:
#A4
(df.isnull().sum() > 0).sum()

np.int64(4)

In [8]:
#A5
result = df.groupby('origin')['fuel_efficiency_mpg'].max()
result.loc['Asia']

np.float64(23.759122836520497)

In [9]:
#A6
df['horsepower'].median()

np.float64(149.0)

In [10]:
horsepower_mode = df["horsepower"].mode()[0]
df_filna = df['horsepower'].fillna(horsepower_mode)
df_filna.median()

np.float64(152.0)

In [11]:
#A7
df_filter = df[df['origin'] == 'Asia']
df_filter = df_filter[['vehicle_weight','model_year']]
df_filter = df_filter.head(7)

In [12]:
X = df_filter.to_numpy()
X_T = X.T
XTX = np.dot(X_T, X)
XTX_inv = np.linalg.inv(XTX)

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w = (XTX_inv @ X_T) @ y
w.sum()

np.float64(0.5187709081074016)

# Note

In [13]:
u = np.array([2,4,5,3])
v = np.array([1,2,3,4])
u_T = u.T
u_T

array([2, 4, 5, 3])

In [14]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# Inverse must be 2D array or higher
np.random.seed(123)
A = np.random.rand(2,2)
A

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477]])

In [16]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 1.72792025, -0.89681245],
       [-0.71099351,  2.18286046]])

In [17]:
A @ A_inv

array([[ 1.00000000e+00, -4.24169562e-17],
       [-5.68920827e-17,  1.00000000e+00]])